n1 = input('\033[4;31mtype it a number or a text:')
print(type(n1))
print('this is a number? {}'.format(n1.isnumeric()))
print('this is a text? {}'.format(n1.isalpha()))
print('this is a decimal number? {}'.format(n1.isdecimal()))
print('this is a alphanumeric? {}'.format(n1.isalnum()))
print('this is a space? {}'.format(n1.isspace()))
print('this is a capital letter? {}'.format(n1.isupper()))
print('this is a lowercase letter? {}'.format(n1.islower()))